services:
  db_service:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mood_tracker_db
      MYSQL_USER: kelasf
      MYSQL_PASSWORD: TekserF-2025
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  app_service:
    build: .
    container_name: express_app
    restart: always
    environment:
      DB_HOST: db_service
      DB_USER: kelasf
      DB_PASS: TekserF-2025
      DB_NAME: mood_tracker_db
    depends_on:
      - db_service

  nginx_service:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service

volumes:
   db_data:
